# Generated by Django 3.0.8 on 2020-07-09 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=200)),
                ('jobtitle', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=200)),
                ('phoneno', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('projectdetail', models.CharField(max_length=1000)),
                ('User_profiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_testing.User_profiles')),
            ],
        ),
    ]
